name: senta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - cudnn=8.8
  - pip
  - pip:
      - fastapi==0.115.4
      - uvicorn==0.32.0
      - numpy==2.0.2
      - pytest==8.3.3
      - pytest-benchmark==5.0.0
      - tensorflow==2.18.0
      - tf-keras==2.18.0
      - transformers==4.46.1
      - tokenizers
      - httpx==0.27.2
      - starlette==0.41.2
      - typing-extensions
      - pydantic==2.9.2
      - requests
      - grpcio
      - httpx
